from .data import POLICIES

def score_policy(query: str, policy: dict) -> int:
    q = query.lower()
    return sum(1 for tag in policy["tags"] if tag.lower() in q)

def retrieve(query: str, top_k: int = 3):
    ranked = sorted(POLICIES, key=lambda p: score_policy(query, p), reverse=True)
    ranked = [p for p in ranked if score_policy(query, p) > 0]
    return ranked[:top_k] or POLICIES[:2]

def classify(query: str):
    q = query.lower()
    if any(x in q for x in ["phishing","malware","unauthorized access","suspicious email"]):
        return "security_incident", "Security", "critical"
    if "password" in q or "locked out" in q or "account" in q and "lock" in q:
        return "password", "IT", "high"
    if "vpn" in q:
        return "vpn", "IT", "high"
    if "printer" in q:
        return "printer", "IT", "medium"
    if "mailbox" in q or "email" in q and "full" in q:
        return "mailbox", "IT", "medium"
    if "software" in q or "extension" in q or "install" in q:
        return "software", "IT Security", "medium"
    if "guest" in q and ("wifi" in q or "wi-fi" in q):
        return "guest_wifi", "Self-service", "low"
    if "expense" in q:
        return "expense", "Finance", "medium"
    if "monitor" in q or "chair" in q or "home" in q and "equipment" in q:
        return "wfh_equipment", "Manager + Finance", "medium"
    if "laptop" in q or "screen" in q or "hardware" in q:
        return "hardware", "IT", "high"
    if "admin access" in q or "access" in q and "server" in q:
        return "access", "Human review", "high"
    return "unknown", "Human review", "medium"

def respond(query: str):
    intent, route, risk = classify(query)
    docs = retrieve(query)

    if intent == "security_incident":
        answer = ("This should be reported to security@veridian-corp.example immediately. "
                  "The policy also says the suspected phishing email should not be forwarded to other employees.")
        action = "Escalate to Security"
    elif intent == "password":
        answer = ("You can reset your password through the self-service portal. Because the account was locked after more than 5 failed attempts, IT must unlock it manually. No approval is required.")
        action = "Route to IT for manual unlock"
    elif intent == "vpn":
        answer = ("VPN credentials expire every 90 days and must be renewed by the employee. Full-time employees receive VPN access automatically; contractors require manager approval through the access request form.")
        action = "Renew credentials / route access approval if contractor"
    elif intent == "printer":
        answer = ("First check the printer queue and restart the print spooler. If the issue persists, log a ticket including the printer asset tag.")
        action = "Self-service troubleshooting"
    elif intent == "mailbox":
        answer = ("The default mailbox quota is 25GB. Archive old mail when nearing the limit. A quota increase above 25GB needs manager approval and can go up to 50GB.")
        action = "Archive mail / manager approval for increase"
    elif intent == "software":
        answer = ("Standard software in the approved catalog can be self-installed. Non-catalog software requires IT Security review, which takes 3–5 business days.")
        action = "IT Security review"
    elif intent == "guest_wifi":
        answer = ("Guest Wi-Fi credentials are valid for 24 hours and can be generated by any employee at the front-desk kiosk. No IT ticket is required.")
        action = "Use front-desk kiosk"
    elif intent == "expense":
        answer = ("Finance grants access to the expense management tool. IT can help only with login or technical issues after an account already exists.")
        action = "Finance for access; IT for technical login issues"
    elif intent == "wfh_equipment":
        answer = ("Employees working remotely more than 3 days per week are eligible for a one-time home-office equipment allowance for a chair or monitor. Manager sign-off and Finance processing are required; IT handles shipping after approval.")
        action = "Manager sign-off → Finance → IT shipping"
    elif intent == "hardware":
        answer = ("Laptop replacement is eligible after 3 years, or earlier for verified hardware failure. Requests should be raised at least 2 weeks before intended replacement. The asset policy also describes a standard 4-year refresh cycle and says early replacement outside that cycle requires Finance sign-off plus IT approval.")
        action = "IT assessment / replacement workflow"
    elif intent == "access":
        answer = ("The supplied policy data does not provide a general rule for this server-admin access request. A human review is required rather than inventing an approval path.")
        action = "Human review"
    else:
        answer = ("I can help with the supplied IT policies, but this request is too vague to safely resolve from the source data. Please provide the affected system or issue.")
        action = "Ask for clarification"

    return {
        "answer": answer,
        "intent": intent,
        "route": route,
        "risk": risk,
        "action": action,
        "sources": [{"id": d["id"], "title": d["title"], "text": d["text"]} for d in docs],
    }
